baseURL: "https://rohanarni.com/"
languageCode: en-us
title: rohanarni.com
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "Rohan Arni"
    subtitle: "Hi there! I’m a senior at High Technology High School. I'm interested in physics, philosophy, history, artificial intelligence, and more."
    imageUrl: img/profile.png
    buttons:
      - name: Blog
        url: "/posts"
      - name: Newsletter
        url: "/newsletter"
      - name: GitHub
        url: "https://github.com/rtenacity"


      
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: posts
      name: Posts
      url: /Posts/
      weight: 20
    - identifier:  
      name: Archives
      url: /archives/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 40
    - identifier: newsletter
      name: Newsletter
      url: /newsletter/
      weight: 10
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary


services:
  disqus:
    shortname: rohanarni
